[package]
name = "json5"
version = "0.2.5"
authors = ["Callum Oakley <c.oakley108@gmail.com>"]
description = "A Rust JSON5 serializer and deserializer which speaks Serde."
license = "ISC"
repository = "https://github.com/callum-oakley/json5-rs"
readme = "README.md"
keywords = ["json5", "parse", "parser", "serde", "json"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"
